### ISSUE TITLE
Apps: displayRange min and max should be numbers

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/microbiomeComputations#17]
Running mbio locally right now with the latest web-eda code gives an error in 
GEMS > Ranked abundance > Genus data and ranking method=median > boxplot

```
TypeError: value.toFixed is not a function
    at numberDecimalPoint (number-decimal-point.js:3:1)
    at computeDefaultDependentAxisRange.js:56:26
    at updateMemo (react-dom.development.js:15463:1)
    at Object.useMemo (react-dom.development.js:15920:1)
    at useMemo (react.development.js:1521:1)
    at useDefaultDependentAxisRange (computeDefaultDependentAxisRange.js:31:46)
    at BoxplotViz (BoxplotVisualization.js:247:39)
```

Figured out that the change in web-eda commit `3b28dba8cd1a7ccdcf25` (removing the multiplication by 1.05) meant that the inputs to `numberDecimalPoint` were sometimes still strings, hence the error above. This was only an issue when we use info from computedVariableMetadata to decide default max and min. 

All in all, we should just send display ranges as numbers instead of strings. They are numbers in the variable metadata (for continuous variables).

**Comment by asizemore** [comment]
Closed with https://github.com/VEuPathDB/web-eda/issues/1107

**Comment by asizemore** [comment]
Nothing to QA, moving to complete
