### ISSUE TITLE
Beta div failing with pathways

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/microbiomeComputations#65]
Noticed on both live and qa.

Example (qa): 
<img width="1159" alt="Screen Shot 2023-12-05 at 6 28 26 AM" src="https://github.com/VEuPathDB/microbiomeComputations/assets/11710234/ad19843f-60ca-4587-b2a2-69bf64e0fd65">

R output:
```
Rserve started in non-daemon mode.
[1] "starting beta diversity computation"

2023-12-05 10:41:13 Received df table with 574 samples and 435 taxa.

2023-12-05 10:41:13 Replaced NAs with 0

2023-12-05 10:41:14 Computed dissimilarity matrix.
Error in eigen(delta1) : infinite or missing values in 'x'
In addition: Warning messages:
1: no function found corresponding to methods exports from ‘veupathUtils’ for: ‘asJSON’
2: replacing previous import ‘data.table::as.data.table’ by ‘veupathUtils::as.data.table’ when loading ‘plot.data’
3: replacing previous import ‘veupathUtils::toJSON’ by ‘jsonlite::toJSON’ when loading ‘plot.data’
4: replacing previous import ‘data.table::as.data.table’ by ‘veupathUtils::as.data.table’ when loading ‘microbiomeComputations’
5: In data.table::fread("beta_div_input", select = c(OBI_0002623.WholeMetagenomeSequencingAssay_stable_id = "double",  :
  Attempt to override column 1 <<OBI_0002623.WholeMetagenomeSequencingAssay_stable_id>> of inherent type 'string' down to 'float64' ignored. Only overrides to a higher type are currently supported. If this was intended, please coerce to the lower type afterwards.
6: In data.table::fread("beta_div_input", select = c(OBI_0002623.WholeMetagenomeSequencingAssay_stable_id = "double",  :
  Attempt to override column 2 <<EUPATH_0000609.Sample_stable_id>> of inherent type 'string' down to 'float64' ignored. Only overrides to a higher type are currently supported. If this was intended, please coerce to the lower type afterwards.
7: In data.table::fread("beta_div_input", select = c(OBI_0002623.WholeMetagenomeSequencingAssay_stable_id = "double",  :
  Attempt to override column 3 <<EUPATH_0000096.Participant_stable_id>> of inherent type 'string' down to 'float64' ignored. Only overrides to a higher type are currently supported. If this was intended, please coerce to the lower type afterwards.
8: In vegan::vegdist(df[, -..allIdColumns], method = method, binary = TRUE) :
  you have empty rows: their dissimilarities may be
                 meaningless in method “bray”
9: In vegan::vegdist(df[, -..allIdColumns], method = method, binary = TRUE) :
  missing values in results
```

**Comment by asizemore** [comment]
note not _every_ pathway abundance collection is failing. Just some

**Comment by asizemore** [comment]
oof just tried bonus, pathway abundance, bray, and got a different errror:

```
2023-12-13 10:53:54.560 [rid:     ][jid:13487f9497398ff801a626b0a4b2b266][p:betadiv] ERROR PluginExecutor:167 - Failed to fetch tabular data.
 java.lang.RuntimeException: 500 Internal Server Error: {"status":"server-error","message":"Unable to fetch all required data","requestId":"3LSKBOULFZakAFyupimxHJ"}
	at org.gusdb.fgputil.client.ResponseFuture.lambda$getInputStream$0(ResponseFuture.java:49) ~[service.jar:1.0.0]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at org.gusdb.fgputil.functional.Either.leftOrElseThrow(Either.java:149) ~[service.jar:1.0.0]
	at org.gusdb.fgputil.client.ResponseFuture.getInputStream(ResponseFuture.java:48) ~[service.jar:1.0.0]
	at org.veupathdb.service.eda.compute.EDA.getMergeData(EDA.kt:121) ~[service.jar:1.0.0]
	at org.veupathdb.service.eda.compute.exec.PluginExecutor.execute(PluginExecutor.kt:157) ~[service.jar:1.0.0]
	at org.veupathdb.lib.compute.platform.intern.jobs.JobExecutionHandler.execute(JobExecutionHandler.kt:91) ~[service.jar:1.0.0]
	at org.veupathdb.lib.compute.platform.intern.queues.QueueWrapper.onJob(QueueWrapper.kt:94) ~[service.jar:1.0.0]
	at org.veupathdb.lib.compute.platform.intern.queues.QueueWrapper.access$onJob(QueueWrapper.kt:30) ~[service.jar:1.0.0]
	at org.veupathdb.lib.compute.platform.intern.queues.QueueWrapper$3.handle(QueueWrapper.kt:61) ~[service.jar:1.0.0]
	at org.veupathdb.lib.rabbit.jobs.pools.JobHandlers.execute(JobHandlers.kt:18) ~[service.jar:1.0.0]
	at org.veupathdb.lib.rabbit.jobs.QueueWorker.initCallbacks$lambda$5$lambda$3$lambda$2(QueueWorker.kt:82) ~[service.jar:1.0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by d-callan** [comment]
i can confirm this is a case where we have for at least one sample a 0 abundance for all pathways. ive also confirmed that is how the data are in the files produced by the workflow. i have not looked in any depth at the workflow to know if theres something we could do about it there. in any case, i dont think we can ever guarantee we wont get data like this, so maybe our AbundanceData class needs to learn how to prune itself better.

**Comment by d-callan** [comment]
confirmed working w microbiomeComputations v3.3.5
